app:
  name: "EONA TTS API"
  version: "1.0.0"
  debug: false

content_safety:
  enable_ai_check: true
  severity_threshold: 0.7
  max_retries: 3
  
tts:
  max_script_length: 10000
  supported_formats: ["mp3", "wav", "ogg"]
  default_voice: "sarah"
  default_emotion: "friendly"
  
cache:
  ttl: 86400  # 24 hours
  max_size: 1000
  
rate_limiting:
  requests_per_minute: 60
  requests_per_hour: 1000
