version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///./data/eona.db
      - REDIS_HOST=redis
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MURF_API_KEY=${MURF_API_KEY}
      - API_KEY=${API_KEY}
    depends_on:
      - redis
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
